<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="swuni-QA-04" name="org.etna.modules.LoginModule" tests="21" failures="0" timestamp="14 Apr 2016 16:04:32 GMT" time="112.134" errors="5">
  <testcase name="TS_Login_002_TC_Login_016_017_018_rememberMeCheckboxTest" time="10.015" classname="org.etna.modules.LoginModule"/>
  <testcase name="TS_Login_002_TC_Login_012_uncheckRememberMeWhenInAutoFillForm" time="10.680" classname="org.etna.modules.LoginModule"/>
  <testcase name="TS_Login_001_TS_Login_006_TC_Login_001_AsASuperUser_PurchaseAgent_GeneralUser" time="5.185" classname="org.etna.modules.LoginModule"/>
  <testcase name="TS_Login_001_TS_Login_006_TC_Login_001_AsASuperUser_PurchaseAgent_GeneralUser" time="4.663" classname="org.etna.modules.LoginModule"/>
  <testcase name="TS_Login_002_TC_Login_009_010_RememberPassword_UserNameAndPasswordRefill" time="6.630" classname="org.etna.modules.LoginModule"/>
  <testcase name="TS_Login_002_TC_Login_011_AutofillLogin" time="8.492" classname="org.etna.modules.LoginModule"/>
  <testcase name="TS_Login_002_TC_Login_015_rememberMeAsALink" time="4.015" classname="org.etna.modules.LoginModule"/>
  <testcase name="TS_Login_001_TC_Login_008_Verify_Tab_focus" time="1.273" classname="org.etna.modules.LoginModule">
    <error type="org.testng.SkipException" message="having a bug.">
      <![CDATA[org.testng.SkipException: having a bug.
	at org.etna.modules.LoginModule.TS_Login_001_TC_Login_008_Verify_Tab_focus(LoginModule.java:66)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
    </error>
  </testcase> <!-- TS_Login_001_TC_Login_008_Verify_Tab_focus -->
  <testcase name="TS_Login_001_TC_Login_004_005_006_007_ErrorScenarios" time="2.651" classname="org.etna.modules.LoginModule"/>
  <testcase name="TS_Login_001_TS_Login_006_TC_Login_001_AsASuperUser_PurchaseAgent_GeneralUser" time="9.001" classname="org.etna.modules.LoginModule"/>
  <testcase name="TS_Login_002_TC_Login_014_myProductGroupLoginPopupRememberMeClickCheck" time="3.230" classname="org.etna.modules.LoginModule">
    <error type="java.lang.IndexOutOfBoundsException" message="Index: 1, Size: 1">
      <![CDATA[java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
	at java.util.ArrayList.rangeCheck(Unknown Source)
	at java.util.ArrayList.get(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.openqa.selenium.support.pagefactory.internal.LocatingElementListHandler.invoke(LocatingElementListHandler.java:39)
	at com.sun.proxy.$Proxy11.get(Unknown Source)
	at org.etna.customer.pageobjects.ProductsListPageObjects.clickOnMyProductGroup(ProductsListPageObjects.java:214)
	at org.etna.modules.LoginModule.TS_Login_002_TC_Login_014_myProductGroupLoginPopupRememberMeClickCheck(LoginModule.java:211)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
    </error>
  </testcase> <!-- TS_Login_002_TC_Login_014_myProductGroupLoginPopupRememberMeClickCheck -->
  <testcase name="TS_Login_001_TS_Login_006_TC_Login_001_TC_Login_002_TC_Login_024_TC_Login_025_TC_Login_026_TC_Login_027" time="6.054" classname="org.etna.modules.LoginModule"/>
  <testcase name="TS_Login_001_TC_Login_004_005_006_007_ErrorScenarios" time="2.032" classname="org.etna.modules.LoginModule"/>
  <testcase name="TS_Login_004_TC_Login_020_verifyForgotPasswordPage" time="2.943" classname="org.etna.modules.LoginModule"/>
  <testcase name="TS_Login_003_TC_Login_019_verifyRegisterPage" time="2.354" classname="org.etna.modules.LoginModule">
    <error type="org.testng.SkipException" message="Sign up yet to be implemented">
      <![CDATA[org.testng.SkipException: Sign up yet to be implemented
	at org.etna.modules.LoginModule.TS_Login_003_TC_Login_019_verifyRegisterPage(LoginModule.java:255)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
    </error>
  </testcase> <!-- TS_Login_003_TC_Login_019_verifyRegisterPage -->
  <testcase name="TS_Login_001_TC_Login_004_005_006_007_ErrorScenarios" time="2.128" classname="org.etna.modules.LoginModule"/>
  <testcase name="TS_Login_005_TC_Login_021_loginVerifyOrderTopToBottom" time="2.563" classname="org.etna.modules.LoginModule">
    <error type="org.testng.SkipException" message="This feature is having a bug.">
      <![CDATA[org.testng.SkipException: This feature is having a bug.
	at org.etna.modules.LoginModule.TS_Login_005_TC_Login_021_loginVerifyOrderTopToBottom(LoginModule.java:230)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
    </error>
  </testcase> <!-- TS_Login_005_TC_Login_021_loginVerifyOrderTopToBottom -->
  <testcase name="TS_Login_001_TC_Login_004_005_006_007_ErrorScenarios" time="2.686" classname="org.etna.modules.LoginModule"/>
  <testcase name="TS_Login_005_TC_Login_022_loginVerifyOrderBottomToTop" time="20.115" classname="org.etna.modules.LoginModule">
    <error type="org.testng.SkipException" message="This feature is having a bug.">
      <![CDATA[org.testng.SkipException: This feature is having a bug.
	at org.etna.modules.LoginModule.TS_Login_005_TC_Login_022_loginVerifyOrderBottomToTop(LoginModule.java:237)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
    </error>
  </testcase> <!-- TS_Login_005_TC_Login_022_loginVerifyOrderBottomToTop -->
  <testcase name="TS_Login_001_TC_Login_004_005_006_007_ErrorScenarios" time="3.166" classname="org.etna.modules.LoginModule"/>
  <testcase name="TS_Login_001_TC_Login_004_005_006_007_ErrorScenarios" time="2.258" classname="org.etna.modules.LoginModule"/>
</testsuite> <!-- org.etna.modules.LoginModule -->
